version: "3.8"

services:
  # Servicio de base de datos MySQL
  db:
    image: mysql:8.0
    container_name: uniride_db
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306" 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Servicio de la aplicación Django
  web:
    build: .
    container_name: uniride_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      # Volumen para fotos
      - ./media:/app/media 
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true

# Volúmenes para persistencia de datos
volumes:
  mysql_data: