# Generated by Django 5.0.2 on 2026-04-17 02:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('foto_perfil', models.FileField(blank=True, null=True, upload_to='perfiles/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('identificacion', models.FileField(blank=True, null=True, upload_to='identificaciones/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'pdf'])])),
                ('licencia', models.FileField(blank=True, null=True, upload_to='licencias/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'pdf'])])),
                ('es_pasajero', models.BooleanField(default=True)),
                ('es_conductor', models.BooleanField(default=False)),
                ('verificado_identidad', models.BooleanField(default=False)),
                ('verificado_conductor', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'db_table': 'Cuenta',
            },
        ),
    ]
