# Generated by Django 5.0.2 on 2026-04-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=20)),
                ('tipo_entidad', models.CharField(choices=[('viaje', 'Viaje'), ('solicitud', 'Solicitud')], max_length=20)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'Estado',
                'ordering': ['tipo_entidad', 'nombre_estado'],
                'unique_together': {('nombre_estado', 'tipo_entidad')},
            },
        ),
    ]
